name: tsting CI Flow

on: 
  push:
    branches: [master]
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up go
        uses: actions/setup-go@v5

      - name: build
        uses: go build -v ./...


      

